project:
  type: website

website:
  title: "Hugh Bartling"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bartling
      - icon: mastodon
        href: https://fediscience.org/@hughbartling
  page-footer: "Copyright 2024, Hugh Bartling" 
format:
  html:
    theme: solar
    css: styles.css

editor: visual

